"""Service for Google Calendar operations."""
import datetime
from googleapiclient.errors import HttpError
from src.infra.client.google_client import get_calendar_service
from src.modules.agent.dto import ScheduledEventDTO


class CalendarService:
    """Service for managing calendar events."""
    
    @staticmethod
    def add_event(action: str, start_time: datetime.datetime, duration_hours: int = 1) -> ScheduledEventDTO:
        """
        Adds an action as an event to Google Calendar.
        
        Args:
            action: Action description
            start_time: Start time for the event
            duration_hours: Duration in hours (default: 1)
            
        Returns:
            ScheduledEventDTO with event details
            
        Raises:
            HttpError: If calendar API call fails
        """
        service = get_calendar_service()
        end_time = start_time + datetime.timedelta(hours=duration_hours)
        
        event = {
            'summary': action,
            'description': 'Generated by Calendar-Integrated Agent',
            'start': {
                'dateTime': start_time.isoformat(),
                'timeZone': 'UTC',
            },
            'end': {
                'dateTime': end_time.isoformat(),
                'timeZone': 'UTC',
            },
        }

        event = service.events().insert(calendarId='primary', body=event).execute()
        event_link = event.get('htmlLink')
        
        return ScheduledEventDTO(
            action=action,
            start_time=start_time,
            end_time=end_time,
            event_link=event_link
        )
