"""Service for Google Calendar operations."""
import logging
import datetime
from googleapiclient.errors import HttpError
from src.infra.client.google_client import get_calendar_service
from src.modules.agent.dto import ScheduledEventDTO

logger = logging.getLogger(__name__)


class CalendarService:
    """Service for managing calendar events."""
    
    @staticmethod
    def add_event(action: str, start_time: datetime.datetime, duration_hours: int = 1) -> ScheduledEventDTO:
        """
        Adds an action as an event to Google Calendar.
        
        Args:
            action: Action description
            start_time: Start time for the event
            duration_hours: Duration in hours (default: 1)
            
        Returns:
            ScheduledEventDTO with event details
            
        Raises:
            HttpError: If calendar API call fails
        """
        logger.debug(f"Creating calendar event: '{action}' at {start_time}")
        try:
            service = get_calendar_service()
            end_time = start_time + datetime.timedelta(hours=duration_hours)
            
            event = {
                'summary': action,
                'description': 'Generated by Calendar-Integrated Agent',
                'start': {
                    'dateTime': start_time.isoformat(),
                    'timeZone': 'UTC',
                },
                'end': {
                    'dateTime': end_time.isoformat(),
                    'timeZone': 'UTC',
                },
            }

            event = service.events().insert(calendarId='primary', body=event).execute()
            event_link = event.get('htmlLink')
            logger.info(f"Calendar event created: {event_link}")
            
            return ScheduledEventDTO(
                action=action,
                start_time=start_time,
                end_time=end_time,
                event_link=event_link
            )
        except HttpError as e:
            logger.error(f"HTTP error creating calendar event: {e}", exc_info=True)
            raise
        except Exception as e:
            logger.error(f"Failed to create calendar event: {e}", exc_info=True)
            raise
